# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico
version: 2

# Personal info
name: Yuanjie (Roger) Xia
title: PhD Candidate | SENSE Lab, University of Waterloo
email: yuanjie.xia@uwaterloo.ca
website: https://github.com/Yuanjie-Xia

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: Yuanjie-Xia
linkedin_username: roger-xia-5aa419197

# About Section
about_title: About
about_profile_image: images/profile.jpg
about_content: |
  I am a PhD candidate at University of Waterloo working in the SENSE Lab. My research focuses on software engineering, with broader interests in performance testing, search-based method, and root cause detection.

  My current work explores performance modeling in configurable systems. I am especially interested in methods for modeling system performance behavior and locating performance regressions.

  I am open to discussion and collaboration.

content:
  - title: Selected Publications
    layout: list
    content:
      - layout: top-middle
        title: "Reducing the Length of Field-replay Based Load Testing"
        sub_title: "IEEE Transactions on Software Engineering, 2024"
        link: "https://ece.uwaterloo.ca/~wshang/pubs/YUANJIE_TSE_2024.pdf"
        link_text: PDF
        quote: >
          Yuanjie Xia, Lizhi Liao, Jinfu Chen, Heng Li, and Weiyi Shang.
        description: |
          "Reducing the Length of Field-replay Based Load Testing." *IEEE Transactions on Software Engineering*, 50(8): 1967-1983, 2024.

      - layout: top-middle
        title: "CoMSA: A Modeling-Driven Sampling Approach for Configuration Performance Testing"
        sub_title: "ASE 2023"
        link: "https://ece.uwaterloo.ca/~wshang/pubs/ASE_2023_YUANJIE.pdf"
        link_text: PDF
        quote: >
          Yuanjie Xia, Zishuo Ding, and Weiyi Shang.
        description: |
          "CoMSA: A Modeling-Driven Sampling Approach for Configuration Performance Testing." *The 38th IEEE/ACM International Conference on Automated Software Engineering (ASE 2023).*

  - title: Research & Education Experience
    layout: list
    content:
      - layout: left
        title: Concordia University
        sub_title: Master
        caption: "2019 - 2021"
        link: https://www.concordia.ca/
        description: |
          - Investigating load testing in software field.
          - Learning software engineering skill.

      - layout: left
        title: Concordia University
        sub_title: PhD student
        caption: "2021-2023"
        link: https://www.concordia.ca/
        description: |
          - Researching performance testing in software field.
          - Intern in industry

      - layout: left
        title: University of Waterloo
        sub_title: PhD candidate
        caption: "2023-present"
        link: https://uwaterloo.ca//
        description: |
          - Researching performance testing in software field.
          - Intern in industry



  - title: Research Interests
    layout: text
    content: |
      - Performance testing
      - Performance modeling
      - Root cause detection
      - Search-based method

  - title: Academic Service
    layout: list
    content:
      - layout: left
        title: Reviewer
        sub_title: "19th CCF International Conference on Service Science (ICSS)"
        caption: "Professional Service"
        description: |
          Contributed peer review service for the 19th CCF International Conference on Service Science (ICSS).

      - layout: left
        title: Reviewer
        sub_title: "ACM Transactions on Software Engineering and Methodology (TOSEM)"
        caption: "Professional Service"
        description: |
          Contributed peer review service for *ACM Transactions on Software Engineering and Methodology (TOSEM)*.

# Footer
footer_show_references: false

# Build settings
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
